### ISSUE TITLE
support taskName/taskList on place of callback function

### ISSUE THREAD

**Issue by thecotne** [floatdrop/gulp-watch#170]
so to switch from `gulp.watch` to `gulp-watch` you just need to install `gulp-watch`
add require in gulpfile and remove `gulp.` in any watch task
```javascript
// gulp.watch
gulp.watch(['src/**/**.js', 'spec/**/**.js'], ['js']);

// gulp-watch package
watch(['src/**/**.js', 'spec/**/**.js'], function() {
	gulp.start(['js']);
});

// gulp-watch package with taskName/taskList support
watch(['src/**/**.js', 'spec/**/**.js'], ['js']);
```

**Comment by lbeschastny** [comment]
:+1:

**Comment by lbeschastny** [comment]
The only problem with this functionality is that it'll require `gulp` instance to `start` passed tasks.

Right now `gulp-watch` is gulp-less, which is good thing. It's not recommend for gulp plugins to use `gulp` itself.

Maybe, explicitly calling `gulp.start` in `gulp-watch` callback is actually a better approach?

```
watch(['src/**/**.js', 'spec/**/**.js'], function() {
    gulp.start(['js']);
});
```

**P.S.** I'll be happy to create a pull-request if @floatdrop will think otherwise.

**Comment by floatdrop** [comment]
`gulp.run` is deprecated, and `gulp.start` is internal method, so I don't see how plugin can start tasks from itself. @lbeschastny solution is most accurate at the moment.

You can discuss new watcher in https://github.com/wearefractal/vinyl-fs/issues/86 - it is good time to make `watch` right ;)
