### ISSUE TITLE
Slow work with many files (over 300)

### ISSUE THREAD

**Issue by movie4** [floatdrop/gulp-watch#218]
With a large number of files to watch - events run very slowly

Where find a solution: glob, chokidar or gulp-watch?

Files list example https://gist.github.com/movie4/f7cf8871fc59195aea5a

**Comment by UltCombo** [comment]
Are you using a glob such as `/Volumes/**` or passing ~300 individual paths?

**Comment by movie4** [comment]
Thanks for your reply!

Used this `glob` pattern
```
[ 
  './static/**/*.css',
  './modules/**/*.css',
  './../Volumes/**/*.css',
  '!**/__*.css',
  '!./../Volumes/__*.css',
  '!**/bower_components/**',
  '!./../Volumes/bower_components/**',
  '!**/docs/**',
  '!./../Volumes/docs/**',
  '!**/emails/**',
  '!./../Volumes/emails/**',
  '!**/example/**',
  '!./../Volumes/example/**',
  '!**/node_modules/**',
  '!./../Volumes/node_modules/**'
]
```

**Comment by UltCombo** [comment]
I guess that is hard to optimize. Chokidar installs watchers on all directories that it walks through while matching your glob patterns, so that it can detect when you create files or subdirectories that may match your glob patterns.

My bet is that Chokidar is the bottleneck here, we can explore whether Chokidar provides an option to reduce the number of watchers.

Though, if you are editing huge files very fast, then gulp-watch's reading of the file contents (to emit vinyl files) may be a bottleneck as well.

**Comment by paulmillr** [comment]
You can set `usePolling` to `false` if you want better performance on OS X.

**Comment by UltCombo** [comment]
@paulmillr As far as I can see, `usePolling` is false by default, isn't it? https://github.com/paulmillr/chokidar#performance

**Comment by UltCombo** [comment]
We can't really do much on our side to improve perf in this case. You can try tinkering with Chokidar's [performance options](https://github.com/paulmillr/chokidar#performance), and please open an issue in the Chokidar repository if you still experience performance problems.
