### ISSUE TITLE
it has an error in my project(windows)

### ISSUE THREAD

**Issue by subying** [floatdrop/gulp-watch#259]
in source line 114-116
```js
 if (!baseForced) {
	fileOpts.base = globParent(glob);
}
```
my globs is ['src/html/*.html'],and my filepath is 'C:\\Users\\ys\\mf\\src\\html\\index.html',after this code,the fileOpts.base is '.',it caused the last generated filepath is error.

**Comment by UltCombo** [comment]
That looks odd, glob-parent seems to be working fine [here](https://runkit.com/ultcombo/glob-parent-test). Will need further investigation.

**Comment by subying** [comment]
my env is win10,nodev7.0

**Comment by UltCombo** [comment]
Are you still having issues? Did you find the problem or stop using the plugin?

I haven't had much time to test in a Windows environment, but this may be due to an incompatibility of a dependency with Node v7. With semver's magic, the problem may fix itself eventually (if it hasn't been fixed yet).

I'll add Node v7 to our Linux and Windows CI soon.

**Comment by UltCombo** [comment]
#261

**Comment by subying** [comment]
EN,I still have the problem,but I use the option 'base',it is been solved.

2016-11-19 14:54 GMT+08:00 Fabrício Matté <notifications@github.com>:

**Comment by UltCombo** [comment]
The issue has been fixed, `gulp-watch@4.3.11` now fully supports Node v7 on Windows! 🎉
Thanks for reporting. 😄
