### ISSUE TITLE
detect a directory change

### ISSUE THREAD

**Issue by logorrhea** [floatdrop/gulp-watch#282]
Hi I'm not sure if this is possible, but how do I detect if a directory was created/deleted?

Instructions are clear on passing globs for file patterns, but I'm not sure how that would work for a directory.

**Comment by jwt02180** [comment]
I think what you're looking for is something like this:

`watch('./directoryname', { events: ['addDir', 'unlinkDir'] }, callback);`

I noticed that this plugin defaults to only providing the add, unlink, and change events.
Which is why you have to provide the events for directories yourself, otherwise the glob pattern is pretty standard for directories.

**Comment by logorrhea** [comment]
@jwt02180 oh thank you, adding `addDir` and `unlinkDir` was the piece I was missing.
